repos:
  - repo: https://github.com/psf/black
    rev: '23.10.0'
    hooks:
      - id: black
        name: Code Formatter
        language_version: python3.10

  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        name: Code Style
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.0'
    hooks:
      - id: mypy
        name: Static Type Checker
        language_version: python3.10
        additional_dependencies:
          - 'pydantic'
          - 'sqlalchemy-stubs'
          - 'types-pytz'
          - 'types-requests'
          - 'types-redis'
          - 'types-python-dateutil'